name: sonnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.1
  - openslide
  - pip:
    - -r file:requirements.txt
    - openslide-python==1.1.2
    - torch torchvision torchaudio
